# Generated by Django 3.2.3 on 2021-05-25 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menyusui',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ttl_baby', models.DateField()),
                ('gender', models.IntegerField(choices=[(0, 'Laki Laki'), (1, 'Perempuan')])),
                ('length', models.FloatField()),
                ('weight', models.FloatField()),
                ('lingkar_kepala', models.FloatField()),
                ('is_mpasi', models.BooleanField()),
                ('type', models.IntegerField(choices=[(0, 'MPASI'), (1, 'Awal Menyusui')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
