# Generated by Django 3.2.3 on 2021-05-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20210529_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodingredient',
            name='desc',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
