# Generated by Django 3.2.3 on 2021-06-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20210531_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='karbo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='lemak',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
