# Generated by Django 3.2.3 on 2021-06-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20210601_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='estimated',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
