# Generated by Django 3.2.3 on 2021-06-02 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(null=True, upload_to='recipe/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg', 'webp'])]),
        ),
    ]
